name: GitHub-Profile-3D-Contrib

on:
  schedule:
    - cron: "0 18 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    name: generate-github-profile-3d-contrib
    steps:
      - uses: actions/checkout@v3
      - uses: yoshi389111/github-profile-3d-contrib@0.7.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          USERNAME: ${{ github.repository_owner }}
          SETTING_JSON: .github/profile-3d-settings.json
      - name: Crop SVG to hide donut chart
        run: |
          sed -i 's/height="850"/height="520"/g' profile-3d-contrib/profile-night-view.svg
          sed -i 's/viewBox="0 0 1280 850"/viewBox="0 0 1280 520"/g' profile-3d-contrib/profile-night-view.svg
      - name: Commit & Push
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add -A .
          git commit -m "generated 3d profile contrib" || exit 0
          git pull --rebase origin main
          git push
